//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package org.gskbyte.ui.iconifiedMainMenuList;

import android.app.Activity;
import android.content.Context;
import android.util.AttributeSet;
import android.widget.ImageView;
import android.widget.TextView;
import org.gskbyte.R.id;
import org.gskbyte.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class EntryView_
    extends EntryView
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public EntryView_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        title = ((TextView) findViewById(id.title));
        icon = ((ImageView) findViewById(id.icon));
        subtitle = ((TextView) findViewById(id.subtitle));
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.icon_menu_item, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static EntryView build(Context context, AttributeSet attrs) {
        EntryView_ instance = new EntryView_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

}
